import Foundation

/// Drives DocC (Swift) or rustdoc (Rust) to regenerate API documentation.
actor APIDocGenerator {

    enum GeneratorError: Error, Sendable {
        case unsupportedGenerator(String)
        case generationFailed(String)
    }

    private let dryRun: Bool
    /// Maximum wall-clock seconds a doc-generation child process may run before it is
    /// terminated and the call fails. Injectable so tests can use a short value.
    private let timeoutSeconds: Int

    init(dryRun: Bool = false, timeoutSeconds: Int = 120) {
        self.dryRun = dryRun
        self.timeoutSeconds = timeoutSeconds
    }

    func generate(projectPath: String, adapter: ProjectAdapter) async throws -> String {
        switch adapter.apiDocGenerator.lowercased() {
        case "docc":
            return try await generateDocC(projectPath: projectPath, adapter: adapter)
        case "rustdoc":
            return try await generateRustDoc(projectPath: projectPath, adapter: adapter)
        default:
            throw GeneratorError.unsupportedGenerator(adapter.apiDocGenerator)
        }
    }

    func outputPath(projectPath: String, adapter: ProjectAdapter) -> String {
        switch adapter.apiDocGenerator.lowercased() {
        case "docc":
            return projectPath + "/docs/api.md"
        case "rustdoc":
            return projectPath + "/target/doc/index.html"
        default:
            return projectPath + "/docs/api.md"
        }
    }

    /// Test seam: runs a process through the same timeout-guarded runner used in
    /// production and surfaces a non-zero / timeout result as `generationFailed`.
    func runForTesting(
        executable: String,
        args: [String],
        workingDirectory: String
    ) async throws -> Int32 {
        let result = try await runProcess(
            executable, args: args, workingDirectory: workingDirectory)
        if result != 0 {
            throw GeneratorError.generationFailed("process exited \(result)")
        }
        return result
    }

    private func generateDocC(projectPath: String, adapter: ProjectAdapter) async throws -> String {
        let output = outputPath(projectPath: projectPath, adapter: adapter)
        if dryRun {
            let docsDir = URL(fileURLWithPath: projectPath).appendingPathComponent("docs")
            try? FileManager.default.createDirectory(at: docsDir, withIntermediateDirectories: true)
            let url = URL(fileURLWithPath: output)
            if !FileManager.default.fileExists(atPath: url.path) {
                try "# API Reference\n\n> Generated by APIDocGenerator (dry-run)\n"
                    .write(to: url, atomically: true, encoding: .utf8)
            }
            return output
        }

        let result = try await runProcess(
            "/usr/bin/xcodebuild",
            args: ["docbuild", "-scheme", "Merlin", "-derivedDataPath", "/tmp/merlin-docbuild"],
            workingDirectory: projectPath
        )
        if result != 0 {
            throw GeneratorError.generationFailed("xcodebuild docbuild exited \(result)")
        }
        return output
    }

    private func generateRustDoc(projectPath: String, adapter: ProjectAdapter) async throws -> String {
        let output = outputPath(projectPath: projectPath, adapter: adapter)
        if dryRun { return output }

        let result = try await runProcess(
            "/usr/bin/env",
            args: ["cargo", "doc", "--workspace"],
            workingDirectory: projectPath
        )
        if result != 0 {
            throw GeneratorError.generationFailed("cargo doc exited \(result)")
        }
        return output
    }

    /// Runs a child process with a hard timeout. A continuation guarded by an actor-
    /// isolated flag guarantees exactly one resume: whichever of the termination
    /// handler or the timeout watchdog fires first wins; the loser is a no-op.
    private func runProcess(
        _ executable: String,
        args: [String],
        workingDirectory: String
    ) async throws -> Int32 {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: executable)
        process.arguments = args
        process.currentDirectoryURL = URL(fileURLWithPath: workingDirectory)
        process.standardOutput = FileHandle.nullDevice
        process.standardError = FileHandle.nullDevice

        let guardBox = ResumeGuard()
        let deadline = timeoutSeconds

        return try await withCheckedThrowingContinuation { continuation in
            process.terminationHandler = { p in
                Task {
                    guard await guardBox.claim() else { return }
                    continuation.resume(returning: p.terminationStatus)
                }
            }

            // Watchdog: terminate the child and fail if it outlives the deadline.
            Task {
                try? await Task.sleep(nanoseconds: UInt64(deadline) * 1_000_000_000)
                guard await guardBox.claim() else { return }
                if process.isRunning {
                    process.terminate()
                }
                continuation.resume(
                    throwing: GeneratorError.generationFailed("timed out"))
            }

            do {
                try process.run()
            } catch {
                Task {
                    guard await guardBox.claim() else { return }
                    continuation.resume(throwing: error)
                }
            }
        }
    }
}

/// Single-resume guard: the first `claim()` returns true, every later one returns false.
private actor ResumeGuard {
    private var claimed = false
    func claim() -> Bool {
        guard !claimed else { return false }
        claimed = true
        return true
    }
}
