import Foundation

/// Drives DocC (Swift) or rustdoc (Rust) to regenerate API documentation.
actor APIDocGenerator {

    enum GeneratorError: Error, Sendable {
        case unsupportedGenerator(String)
        case generationFailed(String)
    }

    private let dryRun: Bool

    init(dryRun: Bool = false) {
        self.dryRun = dryRun
    }

    func generate(projectPath: String, adapter: ProjectAdapter) async throws -> String {
        switch adapter.apiDocGenerator.lowercased() {
        case "docc":
            return try await generateDocC(projectPath: projectPath, adapter: adapter)
        case "rustdoc":
            return try await generateRustDoc(projectPath: projectPath, adapter: adapter)
        default:
            throw GeneratorError.unsupportedGenerator(adapter.apiDocGenerator)
        }
    }

    func outputPath(projectPath: String, adapter: ProjectAdapter) -> String {
        switch adapter.apiDocGenerator.lowercased() {
        case "docc":
            return projectPath + "/docs/api.md"
        case "rustdoc":
            return projectPath + "/target/doc/index.html"
        default:
            return projectPath + "/docs/api.md"
        }
    }

    private func generateDocC(projectPath: String, adapter: ProjectAdapter) async throws -> String {
        let output = outputPath(projectPath: projectPath, adapter: adapter)
        if dryRun {
            let docsDir = URL(fileURLWithPath: projectPath).appendingPathComponent("docs")
            try? FileManager.default.createDirectory(at: docsDir, withIntermediateDirectories: true)
            let url = URL(fileURLWithPath: output)
            if !FileManager.default.fileExists(atPath: url.path) {
                try "# API Reference\n\n> Generated by APIDocGenerator (dry-run)\n"
                    .write(to: url, atomically: true, encoding: .utf8)
            }
            return output
        }

        let result = try await runProcess(
            "/usr/bin/xcodebuild",
            args: ["docbuild", "-scheme", "Merlin", "-derivedDataPath", "/tmp/merlin-docbuild"],
            workingDirectory: projectPath
        )
        if result != 0 {
            throw GeneratorError.generationFailed("xcodebuild docbuild exited \(result)")
        }
        return output
    }

    private func generateRustDoc(projectPath: String, adapter: ProjectAdapter) async throws -> String {
        let output = outputPath(projectPath: projectPath, adapter: adapter)
        if dryRun { return output }

        let result = try await runProcess(
            "/usr/bin/env",
            args: ["cargo", "doc", "--workspace"],
            workingDirectory: projectPath
        )
        if result != 0 {
            throw GeneratorError.generationFailed("cargo doc exited \(result)")
        }
        return output
    }

    private func runProcess(
        _ executable: String,
        args: [String],
        workingDirectory: String
    ) async throws -> Int32 {
        try await withCheckedThrowingContinuation { continuation in
            let process = Process()
            process.executableURL = URL(fileURLWithPath: executable)
            process.arguments = args
            process.currentDirectoryURL = URL(fileURLWithPath: workingDirectory)
            process.standardOutput = FileHandle.nullDevice
            process.standardError = FileHandle.nullDevice
            process.terminationHandler = { p in
                continuation.resume(returning: p.terminationStatus)
            }
            do {
                try process.run()
            } catch {
                continuation.resume(throwing: error)
            }
        }
    }
}
